### ISSUE TITLE
Shappie needs a facelift.

### ISSUE THREAD

**Issue by slouck** [GATO-Framework/shappie#14]
Getting complaints about his looks.

**Comment by slouck** [comment]
![image](https://github.com/GATO-Framework/shappie/assets/24739467/60c19920-5f71-4fde-b9fb-4960d9eb5f1a)

**Comment by liondw** [comment]
Here's the prompt I used in midjourney:
/imagine character avatar portrait, expressive cat robot, wearing headphones and techwear, blue and white colour scheme, illustration --s 750 --v 5.1 


Here's a short bio:

Shappie // Grumpy Cyberpunk Discord Catbot
Shappie is an annoyed cyber cat living in the discord server attic. They'll begrudgingly give you what you need, adding a healthy serving of snark on the side. While reluctant to say so on a whim, they're hoping for your success and will put in the work to see things through.
